"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2z*&rg!%vl03^jh=ns6-y1k$u)=$3rgdx%fmh#a2%wjhr)z7j4'

# SECURITY WARNING: don't run with debug turned on in production!
# 1. DEBUG режимин өчүрөбүз
# 1. DEBUG режимин өчүрөбүз
DEBUG = True

# 2. Хостторду аныктайбыз
ALLOWED_HOSTS = ['travel-kg-5.onrender.com', 'localhost', '127.0.0.1', '10.0.0.0/8'] # Render ички тармагы үчүн 10.0.0.0/8 кошуп коюу сунушталат

# 3. CSRF коопсуздугу
CSRF_TRUSTED_ORIGINS = ['https://travel-kg-5.onrender.com']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
] # <--- Кашаа жабылганын текшериңиз
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Ушул сапты кошуңуз
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


    # Internationalization
    # https://docs.djangoproject.com/en/6.0/topics/i18n/

# Башка жөндөөлөрдүн астында, эң сол четинде болушу шарт
LANGUAGES = [
    ('ky', 'Kyrgyz'),
    ('ru', 'Russian'),
    ('en', 'English'),
]
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


import os

STATIC_URL = 'static/'

# Сервер файлдарды чогулта турган папка
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Django статикалык файлдарды издей турган папка
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'main', 'static'),
] # Бул жерде кашааны жабууну унутпаңыз!

# Файлдарды кысып, серверге даярдоо
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'