# Generated by Django 6.0.3 on 2026-03-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(default='_', verbose_name='Тур жөнүндө маалымат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(default='-', max_length=100, verbose_name='Жайгашкан жери'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='Мөөнөтү (мис: 7 күн)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.URLField(verbose_name='Сүрөттүн шилтемеси'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баасы'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Турдун аталышы'),
        ),
    ]
