# Generated by Django 6.0.3 on 2026-03-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tour_description_tour_location_alter_tour_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='image',
        ),
        migrations.AddField(
            model_name='tour',
            name='features',
            field=models.CharField(default='-', max_length=200, verbose_name='Өзгөчөлүктөрү (мис: Ат минүү, Кайык)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='image_url',
            field=models.URLField(default=1, verbose_name='Сүрөттүн шилтемеси'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Кыскача маалымат'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(verbose_name='Баасы'),
        ),
    ]
